FROM golang:1.14-alpine

ENV GOPROXY=https://proxy.golang.org
ENV GO111MODULE=on

## add needed libraries
RUN apk upgrade --update-cache --available && apk add ca-certificates build-base git bash sqlite-dev bind-tools && rm -rf /var/cache/apk/*
## add needed certificates
RUN update-ca-certificates

RUN wget -O - -q https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s v1.21.0

RUN go get -u github.com/axw/gocov/gocov
RUN go get -u github.com/cosmtrek/air
RUN go get github.com/go-delve/delve/cmd/dlv

# this instructions will run on actual docker build
ONBUILD ARG SOURCE
ONBUILD WORKDIR $SOURCE
ONBUILD COPY ./go.mod ./go.sum ./
ONBUILD RUN go mod download

